### ISSUE TITLE
help: useFetch - Cannot read property 'isPreview' of undefined

### ISSUE THREAD

**Issue by Teranode** [nuxt-community/composition-api#143]
**📚 What are you trying to do? Please describe.**
I was trying to transition into using the composition API and was going to use fetch but when I use it i get this error:
```
TypeError: Cannot read property 'isPreview' of undefined
```

**🔍 What have you tried?**
This was my previous apprach before composition:
```
    async fetch () {
        this.getEpisodes();
    },
    activated () {
        // Call fetch again if last fetch more than 30 sec ago
        if (this.$fetchState.timestamp <= (Date.now() - 60000)) {
            this.$fetch()
        }
    }, 
```
this is my new approach in transtition:
```
        const { $fetch, $fetchState } = useFetch(async () => {
            getEpisodes()
        })

        onActivated(() => {
            // Call fetch again if last fetch more than 30 sec ago
            if ($fetchState.timestamp <= (Date.now() - 60000)) {
                $fetch()
            }
        })
```
**ℹ️ Additional context**
The getEpisodes method:
```
        let getEpisodes = async function (page) {
            const { data, meta } = await $axios.$get('/api/shows/details/episodes',  { params: { id: params.value.id, page: page } });

            info.episodes = data;
            info.pagination = {
                current_page: meta.current_page,
                last_page: meta.last_page,
                total: meta.total,
                per_page: meta.per_page,
                from: meta.from,
                to: meta.to
            }
        }
```

Upon looking fetch would be called client side and does call the getEpisodes method so i think it has to be something server sided

**Comment by danielroe** [comment]
@Teranode I think this should be fixed in 0.10.4, but do let me know if you have any issues.

**Comment by Teranode** [comment]
@danielroe It renders now, but the isPreview Error is still present in the console logs when it's used.

**Comment by danielroe** [comment]
What version of Nuxt are you using?

**Comment by Teranode** [comment]
im using 2.13.3

**Comment by danielroe** [comment]
Any better luck with 0.10.5?

**Comment by Teranode** [comment]
Yes, that fixed it
