### ISSUE TITLE
fix: ssrRef not usable within onGlobalSetup

### ISSUE THREAD

**Issue by lennartzellmer** [nuxt-community/composition-api#379]
**🐛 The bug**
Since updating to 0.17.0 an `ssrRef` defined within `onGlobalSetup` throws the nuxt error: _Cannot read property 'context' of undefined_

In 0.16.4 it worked fine. It is broken in 0.17.0 and it is still present in 0.20.1.

**🛠️ To reproduce**

1. Go to https://codesandbox.io/s/blue-night-1lyfh?file=/plugins/awesome-plugin.js
2. See error

**🌈 Expected behaviour**
`ssfRef` can be defined within `onGlobalSetup`.

**ℹ️ Additional context**
As recommended I added the `onGlobalSetup` within a plugin

The docs state that using `ssrRef` within `onGlobalSetup` should be possible:
https://composition-api.nuxtjs.org/helpers/ssrRef

**Comment by danielroe** [comment]
Hopefully this is now fixed in `0.20.2` - thanks for reporting it ❤️

**Comment by daikiojm** [comment]
I seems like still not working in `v0.24.4`

![スクリーンショット 2021-06-13 19 34 03](https://user-images.githubusercontent.com/10055293/121803847-58a3af80-cc7e-11eb-9c54-1e25194ba29b.png)

**Comment by danielroe** [comment]
@daikiojm Could you create an issue with a reproduction?
