### ISSUE TITLE
help: exported computed property is not reactive

### ISSUE THREAD

**Issue by claranceliberi** [nuxt-community/composition-api#521]
**📚 What are you trying to do? Please describe.**
I actually have a util function that uses the `@nuxt/auth` module, I have a computed property called `isMe` in my util function to tell me if the user with a certain username is the same as logged in user

```js
// ~util/useAuth.ts

import { computed, defineComponent, useContext, useRoute } from '@nuxtjs/composition-api'
import { useMainModule } from '~/store'

export default function useAuth(username?: string) {

  const route = useRoute()
  const { $auth } = useContext()


  const auth = computed(() => $auth)
  const isMe = computed(() => {
    if  (auth.value.loggedIn) {
      if(username) // if we have provided username, compare it to authanticated user
        return auth.value.user.username === username
       else // unless compare it to username param in the url
        return auth.value.user.username === route.value.params.username
    } else { //there is authenticate so nothing to compare, return false
      return false
    }
  })

  console.log(isMe.value, ' in UserAuth')
  return {
    auth,
    isMe,
  }
}

```

and I am trying to use it in a component 

```js
import {
  computed,
  defineComponent,
  useContext,
  useRoute,
  ref,
  useFetch,
  watch,
} from '@nuxtjs/composition-api'
import { onClickOutside } from '@vueuse/core'

import { SecondNavigationItemInterface } from '~/types/components'
import { useBookReadersModule } from '~/store'
import useAuth from '~/utils/useAuth'

export default defineComponent({
    setup() {
    const { app } = useContext()
    const route = useRoute()
    const bookReadersProfile = useBookReadersModule()
    const username = computed(() => route.value.params.username)
    const usedAuth = useAuth(username.value)
    const isMe = usedAuth.isMe;

    const userFetch = async () => {
      if (!isMe.value && route.value.name.includes('username')) {
        await bookReadersProfile.getBookReadersProfile(username.value)
      } else {
        bookReadersProfile.setBookReadersProfile(app.$auth.user)
      }
    }

    const { fetch } = useFetch(async () => {
      await userFetch()
      //i am expecting that after fetch is called in watch 
      // isMe will have new value when fetched username is same as logged in username
      // but it not being updated on imported value
      // while in userAuth function isMe is updated
    })


    watch(() => route.value.params, (newValue, oldValue) => {
      if (newValue.username !== oldValue.username) {
        fetch()
      }
    })
  
    return {
      isMe,
    }
  },
})

```

any idea of how I can get `isMe` reactivity after import in my component?

**🔍 What have you tried?**
- I made research online for 2 days but nothing works
- I inspected if `isMe` is even reactivity inside `useAuth` file and I found that it is reactive but can't be updated outside of a file when exported
- 
**ℹ️ Additional context**

**Comment by danielroe** [comment]
Fix released in `0.26.0` - let me know if that doesn't work for you.

**Comment by claranceliberi** [comment]
> Fix released in `0.26.0` - let me know if that doesn't work for you.
it doesn't work

**Comment by danielroe** [comment]
@claranceliberi Just taking a surface look at your choice, I'd guess that's because you're 'freezing' a reactive value at a moment in time:
```js
const username = computed(() => route.value.params.username)
const usedAuth = useAuth(username.value)
```
With this, even if the route param update, `useAuth` won't update because setup doesn't get rerun. Instead, you should refactor your code to use computed values, or run functions when a watched value changes.

**Comment by claranceliberi** [comment]
I've just updated my code but still, i am stuck 

```js
    const usedAuth = computed(() => useAuth(username.value))
    const auth = usedAuth.value.auth;
    const isMe = ref(usedAuth.value.isMe);
```

**Comment by danielroe** [comment]
@claranceliberi You are still freezing it at a moment in time. If you prepare a reproduction on https://template.nuxtjs.org I'm happy to give you some help.

**Comment by sinasita** [comment]
@danielroe and @claranceliberi I have the same issue. Did you manage to solve it?

```
  setup(props) {
    const route = useRoute();
    const query = computed(() => route.value.query);

    ...fetching data

    watch(query, (after, before) => {
      const changedQueryParams = getChangedQueryParams(after, before);
      if (changedQueryParams.length) {
        fetch();
      }
    });
```
How to make the route.value.query reactive? I can see the url changing, but the watcher never gets called, not when wrapped in a computed and not when using it like this

`    watch(useRoute(), (after, before) => {`

nor like that

`    watch(route.query, (after, before) => {`
(that's the worst, it causes: 
Invalid watch source: undefined. A watch source can only be a getter/effect function, a ref, a reactive object, or an array of these types. found in...)

Maybe you could help me, that would be awesome.

Thank you so much in advance

**Comment by danielroe** [comment]
Have you tried using `deep`? (If you prepare a reproduction using https://template.nuxtjs.org/ I'd be happy to take a look.)

**Comment by haykkh** [comment]
I was having this same issue, solved it by adding `{ deep: true }`
```js
    watch(
      () => route.value.query,
      (_newQuery) => {
        fetch()
      },
      { deep: true }
    )
```
